Add check for install; Add install retry;

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -119,6 +119,19 @@ jobs:
         with:
           name: server-configs
 
+      - name: Test - Server Downloaded
+        run: |
+          check_for_config() {
+            if ! grep -q -iE "$1" "./docker-log.log"; then
+              printf "Could not find %s in %s\n" "$1" "./docker-log.log"
+              exit 1
+            else
+              printf "Found %s in %s\n" "$1" "./docker-log.log"
+            fi
+          }
+
+          check_for_config "Success! App '376030' fully installed."
+
       - name: Test - Server Started
         run: |
           check_for_config() {
