Initial commit of server files;

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -32,14 +32,14 @@ jobs:
           chmod +x src/run_server.sh
 
       - name: Make Directories
-        run: mkdir REPLACE_ME_CONFIG REPLACE_ME_INSTALL
+        run: mkdir ArkSE_Install ArkSE_Config
 
       - name: Build the Docker Image
         if: ${{ success() }}
         run: |
           docker build \
-          --file docker/steamcmd-dedicated-server-template.Dockerfile \
-          --tag renegademaster/steamcmd-dedicated-server-template:${{ steps.variables.outputs.datetime }} \
+          --file docker/ark-se-dedicated-server.Dockerfile \
+          --tag renegademaster/ark-se-dedicated-server:${{ steps.variables.outputs.datetime }} \
           --build-arg USER_ID=${{ steps.variables.outputs.userid }} \
           --build-arg GROUP_ID=${{ steps.variables.outputs.groupid }} \
           .
@@ -51,17 +51,17 @@ jobs:
         run: |
           docker run \
           --rm \
-          --name dedicated-server \
+          --name ark-se-server \
           --user ${{ steps.variables.outputs.userid }}:${{ steps.variables.outputs.groupid }} \
-          --mount type=bind,source="$(pwd)/REPLACE_ME_INSTALL",target=/home/steam/REPLACE_ME_INSTALL \
-          --mount type=bind,source="$(pwd)/REPLACE_ME_CONFIG",target=/home/steam/REPLACE_ME_CONFIG \
+          --mount type=bind,source="$(pwd)/ArkSE_Install",target=/home/steam/ArkSE_Install \
+          --mount type=bind,source="$(pwd)/ArkSE_Config",target=/home/steam/ArkSE_Config \
           --env=GAME_PORT="25496" \
           --env=MAX_PLAYERS="14" \
           --env=MAX_RAM="6144m" \
           --env=PUBLIC_SERVER="false" \
           --env=SERVER_NAME="GitHubActionTest" \
           --env=SERVER_PASSWORD="github_action_test_password" \
-          steamcmd-dedicated-server-template:${{ steps.variables.outputs.datetime }} \
+          ark-se-dedicated-server:${{ steps.variables.outputs.datetime }} \
           2>&1 | tee ./docker-log.log
 
       - name: Investigate File Structure on Failure
@@ -69,13 +69,13 @@ jobs:
         run: |
           pwd
           echo ''
-          ls -lAuhFn ./REPLACE_ME_INSTALL/
+          ls -lAuhFn ./ArkSE_Install/
           echo ''
-          ls -lAuhFn ./REPLACE_ME_CONFIG/
+          ls -lAuhFn ./ArkSE_Config/
           echo ''
-          tree -aL 4 ./REPLACE_ME_INSTALL/
+          tree -aL 4 ./ArkSE_Install/
           echo ''
-          tree -aL 4 ./REPLACE_ME_CONFIG/
+          tree -aL 4 ./ArkSE_Config/
 
       - name: Upload Docker Logs
         if: ${{ always() }}
@@ -91,9 +91,9 @@ jobs:
         with:
           name: server-configs
           path: |
-            REPLACE_ME_CONFIG/Server/GitHubActionTest.ini
-            REPLACE_ME_CONFIG/Server/GitHubActionTest_SandboxVars.lua
-            REPLACE_ME_INSTALL/ProjectZomboid64.json
+            ArkSE_Config/Server/GitHubActionTest.ini
+            ArkSE_Config/Server/GitHubActionTest_SandboxVars.lua
+            ArkSE_Install/ProjectZomboid64.json
 
   test:
     name: Test Server
@@ -140,11 +140,11 @@ jobs:
       - name: Test - Server JVM Configuration Applied
         run: |
           check_for_config() {
-            if ! grep -q -iE "$1" "./REPLACE_ME_INSTALL/ProjectZomboid64.json"; then
-              printf "Could not find %s in %s\n" "$1" "./REPLACE_ME_INSTALL/ProjectZomboid64.json"
+            if ! grep -q -iE "$1" "./ArkSE_Install/ProjectZomboid64.json"; then
+              printf "Could not find %s in %s\n" "$1" "./ArkSE_Install/ProjectZomboid64.json"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./REPLACE_ME_INSTALL/ProjectZomboid64.json"
+              printf "Found %s in %s\n" "$1" "./ArkSE_Install/ProjectZomboid64.json"
             fi
           }
           
@@ -153,11 +153,11 @@ jobs:
       - name: Test - Server Configuration Applied
         run: |
           check_for_config() {
-            if ! grep -q -iE "$1" "./REPLACE_ME_CONFIG/Server/GitHubActionTest.ini"; then
-              printf "Could not find %s in %s\n" "$1" "./REPLACE_ME_CONFIG/Server/GitHubActionTest.ini"
+            if ! grep -q -iE "$1" "./ArkSE_Config/Server/GitHubActionTest.ini"; then
+              printf "Could not find %s in %s\n" "$1" "./ArkSE_Config/Server/GitHubActionTest.ini"
               exit 1
             else
-              printf "Found %s in %s\n" "$1" "./REPLACE_ME_CONFIG/Server/GitHubActionTest.ini"
+              printf "Found %s in %s\n" "$1" "./ArkSE_Config/Server/GitHubActionTest.ini"
             fi
           }
 
